### PR TITLE
fix right on Block

### PR DESCRIPTION
**Pull request by Charpell**
In the current behaviour, the right props on the Block component does not behave as expected

### CODE REVIEW

**Comment by hetmann** [comment]
@Charpell thanks ... the right option has the correct behaviour for flex content alignment on the main axis.

Take a look at this article https://css-tricks.com/snippets/css/a-guide-to-flexbox/
Visually **justify-content** is a more natural approach compared with **align-items**

We need to add a new option named **align** and have the options: "**left**" & "**right**"

If you don't mind I will close your PR, is it ok?

**Comment by Charpell** [comment]
Great @hetmann , but why does `right` and `bottom` have the same property 
`justifyContent: "flex-end"`

**Comment by hetmann** [comment]
> Great @hetmann , but why does `right` and `bottom` have the same property
> `justifyContent: "flex-end"`

they are similar so it easier to use them when you can a row or column.
- row -> right (flex-end)
- column -> bottom (flex-end)

Is how the semantic is formed: `row element position to right` vs `column element position to bottom`

**Comment by Charpell** [comment]
Understood, you can close the PR

**Comment by hetmann** [comment]
> Understood, you can close the PR

Thank you very much for your support. Keep on the good work.

**Pull request closed without merging**
